# Generated by Django 6.0.2 on 2026-03-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image_url_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.CharField(blank=True, choices=[('steam', 'Steam'), ('epic', 'Epic Games'), ('microsoft', 'Microsoft Store'), ('playstation', 'PlayStation'), ('xbox', 'Xbox'), ('origin', 'Origin'), ('uplay', 'Ubisoft Connect'), ('gog', 'GOG'), ('battle', 'Battle.net'), ('rockstar', 'Rockstar Games'), ('other', 'أخرى')], help_text='المنصة أو نوع المفتاح', max_length=20, null=True),
        ),
    ]
