# Generated by Django 6.0.2 on 2026-03-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='اختر من 2 إلى 5 تاجات، افصل بينهم بفاصلة', max_length=500),
        ),
    ]
