# Generated by Django 6.0.2 on 2026-03-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('offline_games', 'Offline Games'), ('online_games', 'Online Games'), ('game_keys', 'Activate Games'), ('subscriptions', 'Subscriptions'), ('hardware', 'Hardware')], default='offline_games', help_text='اختر القسم الذي يظهر فيه المنتج', max_length=20),
        ),
    ]
