# Generated by Django 6.0.2 on 2026-03-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('text', models.TextField(verbose_name='نص الرأي')),
                ('time_ago', models.CharField(default='منذ يومين', max_length=50, verbose_name='الوقت')),
                ('avatar_color', models.CharField(default='linear-gradient(135deg, #5865F2, #7289DA)', max_length=100, verbose_name='لون الأفاتار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'رأي عميل',
                'verbose_name_plural': 'آراء العملاء',
                'ordering': ['-created_at'],
            },
        ),
    ]
