# Generated by Django 6.0.2 on 2026-03-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.CharField(blank=True, help_text='ميزات صغيرة تحت الوصف (مثل: توصيل فوري, ضمان)', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('offline_games', 'Offline Games'), ('online_games', 'Online Games'), ('game_keys', 'Activate Games'), ('nitro', 'Nitro'), ('software', 'Software'), ('streaming', 'Streaming'), ('pc_parts', 'PC Parts'), ('accessories', 'Accessories')], default='offline_games', help_text='اختر القسم الذي يظهر فيه المنتج', max_length=20),
        ),
    ]
