# Generated by Django 6.0.2 on 2026-03-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_features_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='رابط فيديو YouTube (اختياري)', max_length=500, null=True),
        ),
    ]
