# Generated by Django 6.0.2 on 2026-03-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'تم استلام الطلب'), ('reviewing', 'جاري المراجعة'), ('processing', 'جاري التحضير'), ('shipped', 'تم الإرسال'), ('completed', 'تم التسليم'), ('rejected', 'مرفوض')], default='received', max_length=20),
        ),
    ]
