# Generated by Django 6.0.2 on 2026-03-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'جاري استلام الطلب'), ('received', 'تم استلام الطلب'), ('processing', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('rejected', 'مرفوض')], default='pending', max_length=20),
        ),
    ]
